// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiqhffybrmnkqbpsdrkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcWhmZnlicm1ua3FicHNkcmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDY4MjUsImV4cCI6MjA2NTUyMjgyNX0.W7bk2Fm6qBXftgI1iWL7uqYLUfkrJufHw2VJs0HzcfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);